---
title: "Assignment 1: Introduction"
author: "Laura Piccirillo"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I previously have used R and RStudio for data analysis required during my master's degree, where I was analyzing mostly quantitative deep-sea coral ages, growth rates, heights, widths, etc. I was introduced to R through a biostatistics course during my master's, which is where I began learning the programming language and software. Prior to that, I did some data analysis but was using excel. I have no experience with Git, but I am very interested in learning to use it as I think it would be very useful for my upcoming data analysis during my PhD work, especially so both myself and my advisor can see data from my experiments.

2. Are there any components of the course about which you feel confident?

> Answer: 
I am pretty familiar with RStudio, and have recently started using R Markdown/Quarto documents for my own work, so I am confident in my abilities with using the software. I have basic knowledge of helpful data wrangling and visualization commands as well.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I have not used Git and GitHub before, so that software is new to me, but I am excited to become accustomed to it and be able to efficiently use it for my own work in the future!


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 3) Knitting
When you have completed this document, click the `knit` button. This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
